import Header from '@/componentes/header/Header.jsx';
import Menu_ancla from '@/componentes/menu_ancla/Menu_ancla.jsx';
import Menu from '@/componentes/menu/Menu.jsx';

import './main.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header>
            <Menu/>
        </Header>
        {children}
      </body>
    </html>
  )
}
